#get node image
FROM node:12
#make /app folder in docker
WORKDIR /app
#copy all the dependencies from local to docker and install them
COPY package.json .
RUN npm install
#cache what is already donwloaded
COPY . .

CMD [ "npm", "run", "build", "&&", "npm", "run", "start"]
