version: '3'
#define services
services: 
    frontend:
        build: frontend
        ports: 
            - "3000:3000"
        volumes: 
            - "./frontend:/app"
    backend:
        build: backend
        ports: 
            - "8000:8000"
        volumes:
            - "./backend:/app"
    database:
        build: database
        ports: 
            - "5000:5000"
        volumes:
            - "./database:/app"